<?php
/**
 * tests/DebugTest.php
 *
 * @package     php-security-txt
 * @link        https://github.com/austinheap/php-security-txt
 * @author      Austin Heap <me@austinheap.com>
 * @version     v0.3.2
 */

namespace AustinHeap\Security\Txt\Tests;

use AustinHeap\Security\Txt\Writer;

require_once 'TestCase.php';

/**
 * DebugTest
 */
class DebugTest extends TestCase
{

    public function testSetDebug()
    {
        $securitytxt = new Writer();

        $securitytxt->setDebug(true);

        $this->assertEquals(true, $securitytxt->getDebug());

        $securitytxt->setDebug(false);

        $this->assertEquals(false, $securitytxt->getDebug());
    }

    public function testEnableDebug()
    {
        $securitytxt = new Writer();

        $securitytxt->setDebug(false);

        $this->assertEquals(false, $securitytxt->getDebug());

        $securitytxt->enableDebug();

        $this->assertEquals(true, $securitytxt->getDebug());
    }

    public function testDisableDebug()
    {
        $securitytxt = new Writer();

        $securitytxt->setDebug(true);

        $this->assertEquals(true, $securitytxt->getDebug());

        $securitytxt->disableDebug();

        $this->assertEquals(false, $securitytxt->getDebug());
    }

    public function testRenderDebug()
    {
        $securitytxt = new Writer();

        $contact = $this->newRandom('testA%s@email.com');
        $result  = $securitytxt->addContact($contact)
                               ->enableDebug()
                               ->execute()
                               ->getText();

        $this->assertContains('Generated by "php-security-txt" v' . PHP_SECURITY_TXT_VERSION, $result);
    }

}
