<?php
/**
 * tests/LaravelTest.php
 *
 * @package     php-security-txt
 * @link        https://github.com/austinheap/php-security-txt
 * @author      Austin Heap <me@austinheap.com>
 * @version     v0.3.2
 */

namespace AustinHeap\Security\Txt\Tests;

use AustinHeap\Security\Txt\Writer;

require_once 'TestCase.php';

/**
 * LaravelTest
 */
class LaravelTest extends TestCase
{

    public function testRenderLaravel()
    {
        uopz_undefine('LARAVEL_SECURITY_TXT_VERSION');
        uopz_undefine('WORDPRESS_SECURITY_TXT_VERSION');

        define('LARAVEL_SECURITY_TXT_VERSION', '0.3.0');

        $securitytxt = new Writer();
        $result      = $securitytxt->addContact($this->newRandom('testA%s@email.com'))
                                   ->setDebug(true)
                                   ->execute()
                                   ->getText();

        $this->assertContains('Generated by "laravel-security-txt" v' . LARAVEL_SECURITY_TXT_VERSION, $result);
    }

}
