<?php
/**
 * tests/WordPressTest.php
 *
 * @package     php-security-txt
 * @link        https://github.com/austinheap/php-security-txt
 * @author      Austin Heap <me@austinheap.com>
 * @version     v0.3.2
 */

namespace AustinHeap\Security\Txt\Tests;

use AustinHeap\Security\Txt\Writer;

require_once 'TestCase.php';

/**
 * WordPressTest
 */
class WordPressTest extends TestCase
{

    public function testRenderWordPress()
    {
        uopz_undefine('LARAVEL_SECURITY_TXT_VERSION');
        uopz_undefine('WORDPRESS_SECURITY_TXT_VERSION');

        define('WORDPRESS_SECURITY_TXT_VERSION', '1.0.0');

        $securitytxt = new Writer();
        $result      = $securitytxt->addContact($this->newRandom('testA%s@email.com'))
                                   ->setDebug(true)
                                   ->execute()
                                   ->getText();

        $this->assertContains('Generated by "wordpress-security-txt" v' . WORDPRESS_SECURITY_TXT_VERSION, $result);
    }

}
